# Generated by Django 4.2.2 on 2023-07-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0003_boleta_alter_producto_precio_alter_producto_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='estado',
            field=models.TextField(blank=True, max_length=40, verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='usuario',
            field=models.CharField(blank=True, max_length=40, verbose_name='usuario'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(blank=True, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(blank=True, verbose_name='Stock'),
        ),
    ]
